### ISSUE TITLE
Generalize blpapi-node binding layer for nested request objects

### ISSUE THREAD

**Issue by ericvw** [bloomberg/blpapi-http#14]
This issue is to track the progress of adding nested object/array support to [blpapi-node](https://github.com/bloomberg/blpapi-node).  Specifically, this support will allow for full usage of the `FieldSearchRequest`.  Please feel free to use this issue as notes, updates, and progress.

**Comment by yupinghu** [comment]
The fix is actually to blpapi-node and is here: https://github.com/yupinghu/blpapi-node/commit/e945d06721cce0bb1bb15335ec1e88e6cbf902db

**Comment by ericvw** [comment]
We have submitted and have gotten merged bloomberg/blpapi-node#35.  We are awaiting @apaprocki to cut a new release of `blpapi-node` that we can depend upon.

**Comment by apaprocki** [comment]
Published v1.0.0 to npm.

**Comment by ericvw** [comment]
@yupinghu, would you like to bump our dependency on `blpapi-node`?

**Comment by yupinghu** [comment]
Sure, this just entails editing the package.json file?
