### ISSUE TITLE
Testing infrastructure

### ISSUE THREAD

**Issue by ericvw** [bloomberg/blpapi-http#18]
We need this.
- We need to decided upon some testing infrastructure (i.e., mocha?)
- How can we stub the BLP API?
- Can the testing infrastructure work with TravisCI?

**Comment by ericvw** [comment]
@ericlu88, we can share this issue and use it for tracking progress/updates on the testing infrastructure.

**Comment by ericlu88** [comment]
Sure, forgot we have an issue for this.

**Comment by ericvw** [comment]
Landed #69 to provide initial infrastructure support for this.

**Comment by ericvw** [comment]
The first and third bullet points have been completed up until this point.  The remaining portion of this issue will now be dedicated towards stubbing the `blpapi-wrapper.ts` for testing purposes.

**Comment by ericlu88** [comment]
After #94 is merged, the left over of this issue is to enhance the testing infrastructure with subscription related functionality.

**Comment by ericvw** [comment]
Closed by #116
