### ISSUE TITLE
Python 2.7/3 examples

### ISSUE THREAD

**Issue by ericvw** [bloomberg/blpapi-http#22]
Provide a complete set of Python 2.7 and Python 3.x examples for accessing the blpapi-http server over HTTPS.  Examples should cover the following:
- Historical data
- Reference data
- Field lookup and search
- Overrides
- Varied options and parameters
- Using different securities that are not just equities (i.e., stocks)
- Getting the result back in some usable language-specific structure

**Comment by j-ruffer** [comment]
The Python 2.7 example presently available specifically targets 2.7.9 Z (see ssl.SSLContext). It's actually quite difficult to get a build of 2.7.9 on most popular Linux distros (even Fedora runs 2.7.8 by default); this example should be revised to be compatible with 2.7.6, which seems to be most common.

**Comment by ericvw** [comment]
@j-ruffer Thanks for noting this.  It is comforting to know that Python has breaking changes across their `patch`/`micro` versions... _*sigh*_.  I will take a look at Python `2.7.6` up to `2.7.9.` and revise the example to work for all the versions in between.

**Comment by ericvw** [comment]
@j-ruffer Alternatively, we are open to PRs if you are inclined? :)

**Comment by j-ruffer** [comment]
@ericvw I'm going to be toying with the API tonight; if I can get something working, then I'll submit a PR!

**Comment by ericvw** [comment]
#49 was contributed.
