### ISSUE TITLE
Support //blp/mktbar

### ISSUE THREAD

**Issue by ericvw** [bloomberg/blpapi-http#55]
This issue is to track the progress of adding support for the `//blp/mktbar` service.  Please update with progress, findings, and status.

**Comment by thmiceli** [comment]
We are currently extracting the subscription service name from the prefix of the security (defaulting to '//blp/mktdata' when not specified).
Do we want to support scenarios where within the same array of subscriptions, securities have different services specified? I would think so but I'd like make sure.

**Comment by yupinghu** [comment]
A quick reading of the current subscription implementation suggests this already should work, but it's worth testing.

**Comment by thmiceli** [comment]
@yupinghu yes it does. I tried mixing mktdata and mktvwap and it works. But we need to be able to listen to events other than just MarketDataEvents, I am working on that.

**Comment by thmiceli** [comment]
Closed with PR #83
