### ISSUE TITLE
Support //blp/tasvc

### ISSUE THREAD

**Issue by ericvw** [bloomberg/blpapi-http#57]
This issue is to track the progress of adding support for the `//blp/tasvc` service.  Please update with progress, findings, and status.

**Comment by thmiceli** [comment]
Partially implemented with PR #83.
Still waiting for example for a subscription to technical analysis service.

**Comment by thmiceli** [comment]
I haven't been able to get a working example for subscription to tasvc.
I may be able to see what's happening by debugging the C++ API calls.

**Comment by ericvw** [comment]
I'm removing this from this milestone to reschedule for another.
