### ISSUE TITLE
Add subscription examples

### ISSUE THREAD

**Issue by yupinghu** [bloomberg/blpapi-http#63]

**Comment by ericlu88** [comment]
Create PR #71 which adds a node.js subscription example using `socket.io`

**Comment by ericvw** [comment]
@ericlu88, are we OK to close this or is there outstanding work?

**Comment by ericlu88** [comment]
@ericvw depends on whether we want to add other language support for subscriptions?

**Comment by ericvw** [comment]
It may be best to itemize the subscription examples into separate issues that target specific languages we want examples are and close this out since we have at least one example.  We should have an issue for each languages we already have a request/response examples for.

**Comment by ericlu88** [comment]
Add #76 #77 #78 for adding other examples.
