### ISSUE TITLE
Update docs for subscriptions, auth, new URL scheme

### ISSUE THREAD

**Issue by yupinghu** [bloomberg/blpapi-http#72]
http-api-guide.md is falling behind a bit:

1) Subscriptions aren't explained.
2) Auth will need to get added when it lands.
3) All the references (as well as examples across the board) will need to be updated for the URL scheme when #59 is resolved).

**Comment by ericvw** [comment]
Examples look to be updated in #74.

**Comment by ericvw** [comment]
I believe `(3)` is covered by #73.

**Comment by ericvw** [comment]
Should we break `(1)` and `(2)` into their own issues so we can assign ownership?

**Comment by ericlu88** [comment]
I prefer having separate issues.

**Comment by yupinghu** [comment]
Let's use this issue to track adding subscriptions in docs, and in general let's have documenting new features be a requirement of closing the issue for that feature (i.e. I'll handle auth as part of implementing auth).

**Comment by ericvw** [comment]
Created #113 and #114 to track documentation for subscriptions and authorization.
