### ISSUE TITLE
blpapi-wrapper should return different error types

### ISSUE THREAD

**Issue by yupinghu** [bloomberg/blpapi-http#79]
Currently, any time the wrapper returns an error, we reject with that error, which gets handled as a 500. We should allow the wrapper to return various error types and surface that to the client.

**Comment by ericvw** [comment]
@yupinghu, can you provide a scenario where we want to do this?

**Comment by yupinghu** [comment]
As discussed in person: e.g. we want to be able to distinguish between bad inputs (e.g. invalid service specified) from, say, server errors, so that we can do a 4xx vs. a 5xx. Eventually things like auth errors will also need this to be distinguishable.

**Comment by ericvw** [comment]
@thmiceli, is going to pick this up.

**Comment by ericvw** [comment]
What's the status of this?

**Comment by thmiceli** [comment]
I haven't actually looked into this yet.
Is there more to do than what was done in https://github.com/bloomberg/blpapi-node/pull/40

**Comment by ericvw** [comment]
Just depending on the `blpapi-node` changes as a npm dependency update should be good enough.  This addresses the `blpapi-wrapper` emitting different error types.

**Comment by thmiceli** [comment]
The dependency is already in package.json. So I don't think there is more to do for this issue. Right?

**Comment by ericvw** [comment]
The dependency is in `package.json`, but we need a new release version of `blpapi-node` to depend upon that has the changes from bloomberg/blpapi-node@e863218ca407c62eb9d7360026c188e29cbf0612.
