### ISSUE TITLE
Inconsistent Response from Historical Data Requests

### ISSUE THREAD

**Issue by aceofsteel** [bloomberg/blpapi-http#99]
During Treehacks, we were seeing responses returning incomplete data(Only 1 field having data returned) or being invalid json objects. I have a feeling it is because the requests are M x N which are causing the issues.

Sample json request that was causing issues: 

``` json
{
   "securities": ["FOXA US Equity", "CTSH US Equity", "APC US Equity"],
    "fields": ["PX_LAST", "OPEN", "EPS_ANNUALIZED"],
    "startDate": "20120601",
    "endDate": "20120602",
    "periodicitySelection": "DAILY"
}
```

**Comment by ericvw** [comment]
@aceofsteel, can you provide more details of the language used that was running into this issue?  `curl` appears to be returning a response with no errors.  I am guessing this is an issue with NodeJS?

**Comment by aceofsteel** [comment]
We were using python 2. Don't have my setup with me now to reproduce. When we ran the request, 3/5 times it was invalid json.

**Comment by ericvw** [comment]
We found that this has always been issue and has recently surfaced as being exposed.  There was async mi-synchronization that was happening.  However, a48f37c of #89 fixes this issue.  We are going to bump the `hackathon` branch to the latest `develop` at cd9195a and bounce `http-api.openbloomberg.com`.

**Comment by ericvw** [comment]
Updated `hackathon` branch and bounced `http-api.openbloomberg.com` - everything looks OK now.
